[theme]
# 主颜色，用于交互元素（按钮，滑块等）。这里用金色。
primaryColor="#FFD700"

# 主背景颜色 (VS Code 暗色风格)
backgroundColor="#1E1E1E"

# 次要背景颜色，用于侧边栏等元素
secondaryBackgroundColor="#252526"

# 文本颜色 (VS Code 代码的科技蓝)
textColor="#9CDCFE"

# 字体
font="sans serif"

